app:
  env: "local"

server:
  host: "localhost"
  port: 9090
  read_timeout: 4s
  write_timeout: 10s

database:
  host: "db"
  port: 5433
  url: ""
  name: ""
  password: ""
  user: ""
  max_connections: 20

jwt:
  secret: ""
  expiration: 24h

logging:
  log_level: "debug"
  format: "text"
